#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Locale-Maketext-Gettext
Version  : 1.28
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/I/IM/IMACAT/Locale-Maketext-Gettext-1.28.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/I/IM/IMACAT/Locale-Maketext-Gettext-1.28.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libl/liblocale-maketext-gettext-perl/liblocale-maketext-gettext-perl_1.28-2.debian.tar.xz
Summary  : Joins gettext and Maketext frameworks
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-3.0
Requires: perl-Locale-Maketext-Gettext-bin = %{version}-%{release}
Requires: perl-Locale-Maketext-Gettext-license = %{version}-%{release}
Requires: perl-Locale-Maketext-Gettext-man = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
Locale::Maketext::Gettext - Joins the gettext and Maketext frameworks
Locale::Maketext::Gettext joins the GNU gettext and Maketext
frameworks.  It is a subclass of Locale::Maketext that follows the
way GNU gettext works.  It works seamlessly, both in the sense of
GNU gettext and Maketext.  As a result, you enjoy both their
advantages, and get rid of both their problems, too.

%package bin
Summary: bin components for the perl-Locale-Maketext-Gettext package.
Group: Binaries
Requires: perl-Locale-Maketext-Gettext-license = %{version}-%{release}
Requires: perl-Locale-Maketext-Gettext-man = %{version}-%{release}

%description bin
bin components for the perl-Locale-Maketext-Gettext package.


%package dev
Summary: dev components for the perl-Locale-Maketext-Gettext package.
Group: Development
Requires: perl-Locale-Maketext-Gettext-bin = %{version}-%{release}
Provides: perl-Locale-Maketext-Gettext-devel = %{version}-%{release}

%description dev
dev components for the perl-Locale-Maketext-Gettext package.


%package license
Summary: license components for the perl-Locale-Maketext-Gettext package.
Group: Default

%description license
license components for the perl-Locale-Maketext-Gettext package.


%package man
Summary: man components for the perl-Locale-Maketext-Gettext package.
Group: Default

%description man
man components for the perl-Locale-Maketext-Gettext package.


%prep
%setup -q -n Locale-Maketext-Gettext-1.28
cd ..
%setup -q -T -D -n Locale-Maketext-Gettext-1.28 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Locale-Maketext-Gettext-1.28/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Locale-Maketext-Gettext
cp COPYING %{buildroot}/usr/share/package-licenses/perl-Locale-Maketext-Gettext/COPYING
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.0/Locale/Maketext/Gettext.pm
/usr/lib/perl5/vendor_perl/5.28.0/Locale/Maketext/Gettext/Functions.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/maketext

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Locale::Maketext::Gettext.3
/usr/share/man/man3/Locale::Maketext::Gettext::Functions.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Locale-Maketext-Gettext/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/maketext.1
